- index.js
- src/editors/_shared/index.js
- Export `useDataTypes` hook to be used in Annotation Editor
- Export editors shared components
> Export useDataTypes and editors shared components

- src/plugins/views/MainMenu/MainMenu.jsx
Related to https://movai.atlassian.net/browse/FP-1961
Tooltip was not being shown when icon was being provided a function component instead of a Material UI icon directly.
> FP-1961 - Fix tooltip not showing for function components in MainMenu

- src/plugins/views/MainMenu/MainMenu.jsx
- src/plugins/views/SystemBar/builder/buildSubMenus.js
The displayed name for creating new editor is the scope name from BE, we should use a FE defined name. This pull request solves that.
> display docType name instead of docType scope

- CHANGELOG.md
- src/plugins/Dialog/Dialog.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
- src/stories/components/PluginManager/PluginManager.stories.jsx
[FP-2073](https://movai.atlassian.net/browse/FP-2073)
- There was an issue when trying to close an untitled document. It was introduced on PR #31. Fixed, mantaining the same logic that fixed the previous issue.
**UPDATE**:
- My previous fix didn't take into account that saving was having the same issue as per @PedroCristovao-Movai's comment: https://github.com/MOV-AI/frontend-npm-lib-ide/pull/35#pullrequestreview-1138848969
- Also found an issue where when we had a new file (untitled) and just picked "Don't save" when you tried to close the tab or refresh the browser it would also trigger the `onUnload` browser function (because although we closed the tab and discarded changes for `untitled` file it still existed in the store). This was also fixed :heavy_check_mark: 
- Also found an issue …
> FP-2073 : Allow to close untitled document

- CHANGELOG.md
- src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
- [FP-2147 - Search nodes in flow not working with strings with low characters](https://movai.atlassian.net/browse/FP-2147)
> Fp 2147 search nodes in flow not working with strings with low characters

- src/plugins/views/Tabs/hooks/useTabLayout.js
[FP-2097](https://movai.atlassian.net/browse/FP-2097)
- The welcome page wasn't being added to the Tab Stack when it was first opened. Adding it to the tabStack seems to fix this issue.
- Also removed some dead code.
> FP-2097 : Close tab doesn't remove bookmarks when localStorage is deleted

- src/decorators/withMenuHandler.jsx
[FP-2157](https://movai.atlassian.net/browse/FP-2157)
- If `undefined` or a tab that doesn't exist was passed to `withMenuHandler` it would not update the menus. Now it does.
> FP-2157 : Added validation for invalidTab to update menus

- src/plugins/views/Explorer/Explorer.jsx
[FP-2096](https://movai.atlassian.net/browse/FP-2096)
**NOTE**: This is a duplicate solution for [Paulo's PR](https://github.com/MOV-AI/frontend-npm-lib-ide/pull/65)
- We believe there might be a bug in the @remixproject library where it is calling the `on` function with previous data. Might also be something regarding the `off` function not working correctly
> FP-2096: Alternative to Paulo's solution

- src/store/BaseStore.js
[FP-2252](https://movai.atlassian.net/browse/FP-2252)
* According to David Dias print screen of the error, I added a small optional chaining validation to prevent blowing up the save in the future.
[FP-2252]: https://movai.atlassian.net/browse/FP-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2252: Added optional chaining to prevent breaking save

- src/editors/Flow/view/Core/Graph/GraphValidator.js
- src/editors/Flow/view/Flow.jsx
[FP-2253](https://movai.atlassian.net/browse/FP-2253)
* For some reason we are losing the context of the real interface when fixing invalid links (it actually happens when we open the fix links modal)
* This PR fixes the specific issue with the invalid links fix
**This PR was cherry-picked from PR #98 the code is exactly the same. The issue @PedroCristovao-Movai had with this PR wasn't directly with this PR, was something else that already entered master. When I tested this, I indeed wasn't able to copy/paste nodes with the shortcuts. But after re-merging master everything was working fine.**
[FP-2253]: https://movai.atlassian.net/browse/FP-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2253: Added a fix for flow losing interface context

- CHANGELOG.md
- package-lock.json
- package.json
- src/App/BaseApp.js
- src/plugins/views/MainMenu/MainMenu.jsx
[FP-2406](https://movai.atlassian.net/browse/FP-2406)
**This merge should only occur after [react #218](https://github.com/MOV-AI/frontend-npm-lib-react/pull/218) gets merged and a new release is out, or it might break the IDE**
* Added a way to make it look like the menu is persistent if it gets unmounted.
* Minor refactor
* This is a hack that had to be done because `MainMenu` keeps getting mount/unmounted due to the complexity of some remix parts. I don't like this, but seems to work without side effects (from what I tested)
[FP-2406]: https://movai.atlassian.net/browse/FP-2406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2406: Make menu be able to persist on IDE

- CHANGELOG.md
- src/decorators/withBookmarks.jsx
- src/editors/Flow/view/Components/Debugging/DependencyInfo.jsx
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Views/BaseFlow.jsx
[FP-2277](https://movai.atlassian.net/browse/FP-2277)
**THIS IS A CHERRY-PICK FROM #140**
* Fixed the issue where clicking on bookmarks caused loss of focus on editor.
* This issue needs to be fixed more in-depth for all editors. This PR also fixes most Flow Editor cases. We need a better filtering from testers where do we need to actually fix the loss of focus.
* Fixed some sonarqube issues
I advise using `activateKeyBind` which editors should have as props (comes from the `withKeybinds` decorator) in the specific scenarios needed,
[FP-2277]: https://movai.atlassian.net/browse/FP-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2277: Give back focus to Flow Editor after losing focus on some cases

- CHANGELOG.md
- src/editors/Flow/view/Core/Graph/GraphBase.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Views/BaseFlow.jsx
[FP-2542](https://movai.atlassian.net/browse/FP-2542)
* Removed flowValidations subscriber from the mainInterface subscriptions (as it doesn't need to be unsubbed / resubbed on the `interfaceSubscriptionsList`).
* Fixed an issue where the Flow wasn't being automatically updated when changes were made on other flows that concerned this one (IE: have a flow1 inside the flow2, toggle expose a node's port on flow1, should be visible on flow2 as soon as we change tabs. This was also preventing the flowValidations to ocurr imediately as opposed to having to refresh the page).
* Removed `MENUS` from the dependencies arrays as it's a const initiated outside of the component (and will never be recreated / changed). 
* Prevented the error throw of `"GraphBase.updateNodeStatus: update for other …
> FP-2542: Removed code that prevented flow validations from running

- database/Callback/backend.DataValidation.py
- scripts/import_callback.sh
[FP-2521](https://movai.atlassian.net/browse/FP-2521)
* Made the backend.Datavalidation regex allow dashes
* Added import_callback script
[FP-2521]: https://movai.atlassian.net/browse/FP-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2521: Made the backend.Datavalidation regex allow dashes 

- CHANGELOG.md
- src/engine/ReactPlugin/EditorReactPlugin.js
[FP-2539](https://movai.atlassian.net/browse/FP-2539)
* Reset bookmarks when we change active tab
[FP-2539]: https://movai.atlassian.net/browse/FP-2539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2539: Reset bookmarks when we change active tab

- package.json
- pnpm-lock.yaml
- src/editors/Node/view/Node.jsx
- src/editors/Node/view/components/IOConfig/IOPorts/components/Parameters.jsx
Fixes [FP-2739](https://movai.atlassian.net/browse/FP-2739): Port properties of the node templates are turning to strings after editing them
:warning: This is a temporary fix, because there are hardcoded strings. Actually the types of the parameters should be coming from the PortsData instead of having for example:
```
{
"name": "out",
"message": "std_msgs/Empty",
"callback": null,
"parameters": {
"latch": false,
"queue_size": 1
}
}
```
We could be having this:
```
{
"name": "out",
"message": "std_msgs/Empty",
"callback": null,
"parameters": {
"latch": {"value": false, "type": "boolean"},
"queue_size": {"value": 1, "type": "number"},
}
}
```
That way the FE can render any input and enforce the type programatically. If not, the backend could also check the types btw and not break the node …
> [FP-2739] Port properties of the node templates are turning to strings after editing them

- CHANGELOG.md
- src/editors/Flow/view/Components/interface/MainInterface.js
- [FP-2744](https://movai.atlassian.net/browse/FP-2744): Copying nodes in the flow does not copy the modified parameters
[FP-2744]: https://movai.atlassian.net/browse/FP-2744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> - [FP-2744](https://movai.atlassian.net/browse/FP-2744): Copying nodes in the flow does not copy the modified parameters

- CHANGELOG.md
- src/editors/Flow/view/Core/Graph/GraphBase.js
- src/editors/Flow/view/Core/Graph/GraphTreeView.js
- src/editors/Flow/view/Flow.jsx
- src/plugins/DocManager/DocManager.js
[FP-2754](https://movai.atlassian.net/browse/FP-2754): Control + S doesn't save flow
- There was a random popup when switching between TreeView and Default mode
- Forcing the focus (keybind) when we switch modes
- Fix app blowing up when we saved in TreeView (not related to this issue, just needed to do File -> Save Document)
[FP-2653](https://movai.atlassian.net/browse/FP-2653): Nodes disappear after updating a flow parameter in tree view mode
- When we save a Flow the onTemplateUpdate is triggered, and the onFlowUpdate is called, this function isn't ready to deal when the flow is in treeview mode and was deleting the Nodes in the TreeView.
[FP-2754]: https://movai.atlassian.net/browse/FP-2754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> Fixed cannot save in TreeView mode

- CHANGELOG.md
- src/engine/ReactPlugin/EditorReactPlugin.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
[FP-2603](https://movai.atlassian.net/browse/FP-2603)
* Fixed issue that was causing active tab change to be called when we did some changes in the same tab.
[FP-2603]: https://movai.atlassian.net/browse/FP-2603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2603: Fixed issue where active tab change was being wrongfully triggered

- CHANGELOG.md
- src/engine/ReactPlugin/EditorReactPlugin.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
- src/plugins/views/Tabs/hooks/useTabStack.js
- src/utils/Utils.js
- src/utils/Workspace.js
[FP-2879](https://movai.atlassian.net/browse/FP-2879)
* ~~Added some sanitization to tabStack onMount~~ This has been removed as was causing other issues and the end result wasn't nearly worth it. I did, however, caught an issue where defaultTabStack was being initialized after being called in `workspace.getTabStack()`.
* We are now also reseting boomarks when we have an invalidTab (ie: there's no more tabs)
* Added a filter before we get the tab stack `getTabStack` to clean out `null` or `undefined` values.
The issue that was happening where sometimes we didn't have tabs and the UI would be weird, it might be solved in this PR (not sure as it's not easily replicable.)
**The actual solution to this ticket's issue is efectively in `src/engine/ReactPlugin/EditorReactPlugin.js` in line 97** …
> FP-2879: Also resetBoomarks when we have an invalidTab

- CHANGELOG.md
- src/editors/Node/view/Node.jsx
- src/editors/Node/view/components/IOConfig/IOPorts/components/Parameters.jsx
- [FP-2739](https://movai.atlassian.net/browse/FP-2739): Port properties of the node templates are turning to strings after editing them
Just applied Vicente's commit. It works.
[FP-2739]: https://movai.atlassian.net/browse/FP-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed FE-2739

- CHANGELOG.md
- package.json
- src/editors/Node/view/Node.jsx
- src/editors/Node/view/components/IOConfig/IOPorts/components/Parameters.jsx
- [FP-2739](https://movai.atlassian.net/browse/FP-2739): Port properties of the node templates are turning to strings after editing them
[FP-2739]: https://movai.atlassian.net/browse/FP-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 1.2.6

- CHANGELOG.md
- src/store/BaseStore.js
- src/store/DBSubscriber/DBSubscriber.js
The main change in this PR is changing the subscription pattern to get updates from changes to _all_ documents, not just those containing Labels. The reason this wasn't done earlier was because it triggered a different bug, which is also fixed in this PR.
The messages of the commits are reproduced here:
> The frontend is not getting the events from Redis when packages are imported. This is because it was only subscribed to records with Labels, and not all records have them. This commit makes the pattern of the subscription wider, so that all events are sent from the backend.
> The code was assuming that the event data of an updated record/document always contained its Name. But sometimes the pattern may not be a subscription to that specific document, but a more generic one (like …
> BP-1200: Fix subscription to doc updates

- CHANGELOG.md
- src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
- [FP-2972](https://movai.atlassian.net/browse/FP-2972):Opening flow when nodes don't exist results in stacktrace
[FP-2972]: https://movai.atlassian.net/browse/FP-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2972: Define missing node

- CHANGELOG.md
- src/engine/ReactPlugin/EditorReactPlugin.js
- src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
- [FP-3001](https://movai.atlassian.net/browse/FP-3001): Clicking backspace on drawer input deletes selected node
- This also make save a global keybind to avoid the shortcut not working with modal or drawer focus
- The branch name was wrong, and this mentioned the scene, which was also an error in part. Although this affects the scene as well, the original ticket did not reference the scene editor.
[FP-3007]: https://movai.atlassian.net/browse/FP-3007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-3001]: https://movai.atlassian.net/browse/FP-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3007: Scene - Search backspace on drawer deletes node

- CHANGELOG.md
- package.json
- [FP-3001](https://movai.atlassian.net/browse/FP-3001): Clicking backspace on drawer input deletes selected node
- [FP-3012](https://movai.atlassian.net/browse/FP-3012): When adding a node, the node list collapses
[FP-3001]: https://movai.atlassian.net/browse/FP-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-3012]: https://movai.atlassian.net/browse/FP-3012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 1.4.2

- CHANGELOG.md
- src/editors/Flow/view/Components/Explorer/Explorer.jsx
- src/editors/Flow/view/Flow.jsx
- src/engine/ReactPlugin/EditorReactPlugin.js
- src/engine/ReactPlugin/ToolReactPlugin.js
- src/plugins/Orchestrator/Orchestrator.ts
- src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
- src/plugins/views/Explorer/Explorer.jsx
- src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
- src/utils/Constants.js
- src/utils/components/Search/Search.jsx
- src/utils/keybinds.js
[FP-3068](https://movai.atlassian.net/browse/FP-3068)
[FP-3069](https://movai.atlassian.net/browse/FP-3069)
* Removed keybind scope from drawers as that was causing some regressions.
* ~Voided keybinds when we are focusing an input / textarea / select unless it strictly has data-scope.~
* Fixed an issue where scope wasn't working because it was lacking a "/".
* Added the keybind on flow search to prevent the popping of browser search when we were typing.
* Now when we select the explorer text input node / link selection will be unselected as to solve #367 
* If for some reason you were able to unselect a link without clicking on the flow, although the link bookmark would disappear, the menu would still show the link information and wouldn't select the details (since the bookmark …
> FP-3068: FP-3069: Removed scope from Drawers. Voided keybinds on inputs

- CHANGELOG.md
- src/store/BaseStore.js
- [FP-2964](https://movai.atlassian.net/browse/FP-2964): IDE - Doc doesn't get dirty when changes are made (so its not saved)
- Tested that when installing ROS package, documents show in UI and have content
- Without label the responses grow in size (10x to 100x)
[FP-2964]: https://movai.atlassian.net/browse/FP-2964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Document doesn't get dirty, add Label to pattern

- CHANGELOG.md
- src/plugins/views/Tabs/hooks/useTabLayout.js
- [FP-3107](https://movai.atlassian.net/browse/FP-3107): IDE: File selection context disappeared
[FP-3107]: https://movai.atlassian.net/browse/FP-3107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3107: IDE: File selection context disappeared

- CHANGELOG.md
- src/editors/Configuration/view/Configuration.jsx
- [FP-3050](https://movai.atlassian.net/browse/FP-3050): Configurations: Toggle between XML and YAML isn't highlighting in real-time
Needs:
https://github.com/MOV-AI/frontend-npm-lib-code-editor/pull/89
[FP-3050]: https://movai.atlassian.net/browse/FP-3050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3050:  Configurations: Toggle between XML and YAML isn't highlighting in real-time

- CHANGELOG.md
- src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
[FP-2639](https://movai.atlassian.net/browse/FP-2639)
* Mantain state of explorer drawer.
* In the case of the scene, if the user enters a scene, the default Scene Tree explorer will be selected (although open/close state will be mantained). If it's open and the user changes to another tab (that doesn't have Scene Tree explorer), the normal Explorer will be loaded.
[FP-2639]: https://movai.atlassian.net/browse/FP-2639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2639: Mantain state of explorer drawer.

- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.test.jsx
[FP-3237](https://movai.atlassian.net/browse/FP-3237)
* Brought back the callback to start robot instead of using REST
* Fixed the issues keeping in mind what was done in #396 
[FP-3237]: https://movai.atlassian.net/browse/FP-3237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3237: Brought back the callback to start robot instead of using REST

- CHANGELOG.md
- src/editors/Flow/view/Components/Nodes/BaseNode/BasePort.js
- src/editors/Flow/view/Components/Tooltips/PortTooltip.jsx
- src/editors/Flow/view/Constants/constants.js
- src/editors/Flow/view/Flow.jsx
[FP-3081](https://movai.atlassian.net/browse/FP-3081)
* We are now handling port modal state manually.
* The port will take 100 ms to close if we just leave out of the port, or 3000 ms when we hover the port (this is the real fix). If we are still hovering the port, it will call for more 3000 ms timeout. If not, it doesn't stay open, it will close after said 3000 ms
* It's so much more controllable now, to the point that I added the ability to also hover over the port tooltip itself. So it will stay opened if the user wants to select any text inside it.
* These values can be adjusted (ofc)
[FP-3081]: https://movai.atlassian.net/browse/FP-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3081: Handling port modal state manually

- CHANGELOG.md
- src/editors/Flow/view/Core/Graph/GraphValidator.js
- src/i18n/languages/en.json
- src/i18n/languages/pt.json
- src/utils/Constants.js
[FP-3254](https://movai.atlassian.net/browse/FP-3254)
* Added instructions to the ROS_VALID_NAMES const errors
[FP-3254]: https://movai.atlassian.net/browse/FP-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3254: Added instructions to the ROS_VALID_NAMES const errors
