- CHANGELOG.md
- index.js
- [FP-2028 : Export missing utilities](https://movai.atlassian.net/browse/FP-2028)
- import { **ERROR_MESSAGES, SUCCESS_MESSAGES** } from "./src/utils/Messages";
- import **Workspace** from "./src/utils/Workspace";
- import { **KEYBINDINGS** } from "./src/utils/shortcuts";
- import * as **Utils** from "./src/utils/Utils";
- import **LocalStorage** from "./src/utils/LocalStorage";
- import **useDataSubscriber** from "./src/plugins/DocManager/useDataSubscriber";
- import { **usePluginMethods** } from "./src/engine/ReactPlugin/ViewReactPlugin";
> FP-2028 : Export missing utilities

- index.js
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Constants/constants.js
- src/i18n/i18n.js
- src/utils/Constants.js
Some changes were done to help in Debug Lock task https://movai.atlassian.net/browse/FP-1963:
- Include Black listed robots in global constants file
- Export lib translations for consuming apps to decide to use translations or not
> Feature/FP-1963 - debug lock changes

- index.js
- src/App/BaseApp.js
- src/plugins/views/MainMenu/MainMenu.jsx
- src/plugins/views/SystemBar/builder/buildFunctions.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
- src/tools/index.js
Related to https://movai.atlassian.net/browse/FP-1961
Now we can render a tool with dynamic content by passing the tab props when rendering a Tab.
> FP-1961 - Make possible to use a plugin with dynamic content

- src/decorators/styles.js
- src/plugins/views/Explorer/styles.js
- src/plugins/views/MainMenu/styles.js
- [Small style twiks](https://github.com/MOV-AI/frontend-npm-lib-ide/commit/afe40677aa83178952efd060dd6f995d9b991a45)
- Update from main
> New Release

- src/plugins/views/Explorer/Explorer.jsx
- src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
- src/tools/HomeTab/components/QuickAccess.jsx
> more fixes scope name

- src/editors/_shared/KeyValueTable/ParametersEditorDialog.jsx
- src/editors/_shared/hooks/DataTypes/AbstractDataType.js
- src/editors/_shared/hooks/DataTypes/types/BooleanType.js
- src/editors/_shared/hooks/useDataTypes.js
- src/stories/AppCE.jsx
- src/stories/components/DataTypes.stories.jsx
- [Fix default value for boolean type](https://github.com/MOV-AI/frontend-npm-lib-ide/commit/0490db043ccb35c0aed2fbc3724e753130ba1661)
- [By-pass validation if parameter value is to be removed](https://github.com/MOV-AI/frontend-npm-lib-ide/commit/d769c61f0bdcac38b09eefd1eaaaf0d3f33f401e)
> Data types validation: Boolean default value

- src/plugins/Dialog/Dialog.js
- src/plugins/Dialog/components/ConfirmationDialog/ConfirmationDialog.jsx
- src/plugins/Dialog/components/FormDialog/NewDocumentDialog.jsx
- Fixed missing props on Form Dialog
- Refactored some PropTypes and defaultProps
> Fixed missing props on Form Dialog

- src/App/BaseApp.js
- src/decorators/withBookmarks.jsx
- src/decorators/withMenuHandler.jsx
- src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
- src/plugins/views/MainMenu/MainMenu.jsx
- src/stories/components/Bookmarks/BookmarkManager.jsx
- src/stories/components/Bookmarks/Bookmarks.stories.jsx
- src/utils/Constants.js
Implement story to test bookmark manager and fix issues with bookmarks in the left menu.
> Implement story to test bookmark manager

- src/engine/ReactPlugin/EditorReactPlugin.js
- src/engine/ReactPlugin/ToolReactPlugin.js
- src/engine/index.js
- src/store/Store.js
- src/stories/components/Bookmarks/BookmarkManager.jsx
- src/tools/AppShortcuts/AppShortcuts.jsx
- src/tools/AppShortcuts/Shortcuts.jsx
- src/tools/HomeTab/HomeTab.jsx
- src/utils/Utils.js
- [Refactor saveDoc method in Store](https://github.com/MOV-AI/frontend-npm-lib-ide/commit/33404ee8529c30d4cf57e2e786923e6c9e1dea7a)
- [Implement React decorator for tools](https://github.com/MOV-AI/frontend-npm-lib-ide/commit/5ff76376d1c6e64d49fbb6d608df00d5663b68b6)
> Improvements

- src/plugins/Dialog/Dialog.js
- src/plugins/views/Explorer/Explorer.jsx
- src/stories/components/PluginManager/PluginManager.stories.jsx
- [Add new listener to delete document in Explorer](https://github.com/MOV-AI/frontend-npm-lib-ide/pull/33/commits/22e65839f5634556a8b867fda6779f26dbeca5f7)
- [Pass message to custom dialog](https://github.com/MOV-AI/frontend-npm-lib-ide/pull/33/commits/3201a7707f9f8093d6d96e012c519614058038c2)
> Add new listener to delete document in Explorer

- README.md
- src/i18n/languages/en.json
- src/i18n/languages/pt.json
- src/plugins/views/Explorer/Explorer.jsx
- src/stories/_mockLogin.js
- src/utils/Messages.js
[FP-2032](https://movai.atlassian.net/browse/FP-2032)
- Added a success message on document deletion.
> FP-2032 : Added success message on doc deletion

- CHANGELOG.md
- src/editors/Flow/view/Core/Graph/GraphBase.js
- src/editors/Flow/view/Core/Graph/GraphTreeView.js
[FP-2074](https://movai.atlassian.net/browse/FP-2074)
- Fixed a bug that was preventing Containers from triggering the status animation
> FP-2074 : Fix Subflows not animating 

- CHANGELOG.md
- src/editors/Flow/view/Flow.jsx
[FP-2031](https://movai.atlassian.net/browse/FP-2031)
- Removed the possibility of having 2 selections at the same time
- This fixes the issue that opened this ticket 
- Also fixes future issues related with double selection.
> FP-2031 : Only 1 selections allowed on Flow Editor

- src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/contextOptions.js
[FP-2126](https://movai.atlassian.net/browse/FP-2126)
- Context menu options now work correctly
- Refactored a bit, so the baseContextMenuOptions, now also receive the data as param and send them to the respective bases functions.
> FP-2126 : Fixed issues with context menu options not working

- src/editors/_shared/DetailsMenu/styles.js
- src/plugins/views/Explorer/components/ListItemTree/ListItemsTreeWithSearch.jsx
- src/plugins/views/Explorer/components/ListItemTree/styles.js
- src/plugins/views/MainMenu/styles.js
- src/plugins/views/SystemBar/styles.js
[FP-2159](https://movai.atlassian.net/browse/FP-2159)
- Fixed some small visual issues
> FP-2159 : Fixed small visual issues

- CHANGELOG.md
- src/plugins/DocManager/DocManager.js
- [FP-2152 - Create new editor will close editor window](https://movai.atlassian.net/browse/FP-2152)
> Fp 2152 create new editor will close editor window

- src/App/AppSettings.js
- src/App/BaseApp.js
- src/plugins/views/MainMenu/MainMenu.jsx
- src/plugins/views/MainMenu/styles.js
[FP-2171](https://movai.atlassian.net/browse/FP-2171)
- Added a new way to pass props to lib-ide to be used in any components.
- Added a way to add the App Menu
- Fixed sonarlint issues
- Minor refactor
> FP-2171 : Added a way to add the App Menu

- src/editors/Flow/view/Utils/utils.js
- src/editors/Node/view/Node.jsx
- src/plugins/DocManager/DocManager.js
- src/stories/_mockLogin.js
[FP-2181](https://movai.atlassian.net/browse/FP-2181)
* Removed function call that was triggering the issue.
* Tested the issue that caused it to be added that was related in this [ticket](https://movai.atlassian.net/browse/FP-2152), it doesn't happen anymore, even without this function call.
* Added some minor refactors that had pending
[FP-2181]: https://movai.atlassian.net/browse/FP-2181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2181: Removed function call that was triggering the issue

- src/engine/ReactPlugin/ToolReactPlugin.js
This is for use in conjunction with the following:
- [ide PR](https://github.com/MOV-AI/frontend-npm-ide/pull/431)
> ToolReactPlugin - remove ToolComponent

- src/App/AppSettings.js
- src/decorators/withBookmarks.jsx
- src/plugins/views/MainMenu/MainMenu.jsx
- src/utils/Utils.js
[FP-2218](https://movai.atlassian.net/browse/FP-2218)
* Added a way to re-add the theme toggle if needed
* Minor refactoring
[FP-2218]: https://movai.atlassian.net/browse/FP-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2218: Added a way to re-add the theme toggle if needed

- src/editors/Flow/view/Components/Explorer/Explorer.jsx
- src/stories/_mockLogin.js
[FP-2232](https://movai.atlassian.net/browse/FP-2232)
[FP-2232]: https://movai.atlassian.net/browse/FP-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2232: No longer showing own flow from add Flow menu

- CHANGELOG.md
- src/App/BaseApp.js
- src/editors/Callback/view/Callback.jsx
- src/engine/ReactPlugin/EditorReactPlugin.js
- src/plugins/DocManager/factory.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
- src/stories/AppCE.jsx
- [FP-2221 - Disable the Language server](https://movai.atlassian.net/browse/FP-2221)
> FP-2221 - Disable the Language server

- CHANGELOG.md
- src/editors/Flow/view/contextOptions.js
[FP-2329](https://movai.atlassian.net/browse/FP-2329)
* Added conditional chaining for context menu
[FP-2329]: https://movai.atlassian.net/browse/FP-2329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2329: Added conditional chaining for context menu

- src/editors/Flow/view/Core/Graph/GraphValidator.js
- src/editors/Flow/view/Flow.jsx
- src/stories/_mockLogin.js
[FP-2253](https://movai.atlassian.net/browse/FP-2253)
* For some reason we are losing the context of the real interface when fixing invalid links (it actually happens when we open the fix links modal)
* This PR fixes the specific issue with the invalid links fix
[FP-2253]: https://movai.atlassian.net/browse/FP-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2253: Added a fix for flow losing interface context

- src/editors/Flow/view/Core/Graph/GraphValidator.js
- src/editors/Flow/view/Flow.jsx
Reverts MOV-AI/frontend-npm-lib-ide#98
> Revert "FP-2253: Added a fix for flow losing interface context"

- CHANGELOG.md
- src/editors/Flow/model/Flow.js
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Components/Menus/ContextMenu/ContextMenu.jsx
- src/editors/Flow/view/Components/Menus/ContextMenu/FlowContextMenu.jsx
- src/editors/Flow/view/Components/Nodes/BaseNode/TreeView/TreeNode.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/contextOptions.js
- src/i18n/languages/en.json
- src/i18n/languages/pt.json
- src/utils/Messages.js
- src/utils/Utils.js
[FP-2348](https://movai.atlassian.net/browse/FP-2348)
* Added the context menu to nodes in tree view (similar to what we had before)
* Added a way to pass disabled prop to items in context menus
* Fixed a few files (sonarqube complaints)
[FP-2348]: https://movai.atlassian.net/browse/FP-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2348: Added context menu to nodes in tree view

- CHANGELOG.md
- src/App/AppSettings.js
- src/plugins/views/SystemBar/builder/buildMenus.js
- src/tools/HomeTab/components/QuickAccess.jsx
[FP-2319](https://movai.atlassian.net/browse/FP-2319)
* Removed all references to forum
[FP-2319]: https://movai.atlassian.net/browse/FP-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2319: Removed all references to forum

- CHANGELOG.md
- src/editors/Flow/view/Components/FlowTopBar/hooks/useNodeStatusUpdate.js
- src/i18n/languages/en.json
- src/i18n/languages/pt.json
- src/stories/_mockLogin.js
[FP-2250](https://movai.atlassian.net/browse/FP-2250)
* I couldn't reproduce the issue, so, just for safety, added a debounce for the robot status going offline snackbar
* Added missing translations
[FP-2250]: https://movai.atlassian.net/browse/FP-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2250: Added a debounce for the robot status going offline snackbar

- CHANGELOG.md
- src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
- src/editors/Flow/view/Components/Menus/sub-components/TableKeyValue.jsx
- src/editors/Flow/view/Components/Menus/sub-components/collapsibleSections/PropertyItem.jsx
- src/utils/Utils.js
[FP-2411](https://movai.atlassian.net/browse/FP-2411)
* Now we only save flow `nodeInstance` parameters when necessary
* Also added a small hack to always save undefined when the user chooses the default option
* Found and fixed an issue where changing the Launch option on a `NodeInstance` wasn't triggering the dirty state on flows
* Small sonarqube fixes
[FP-2411]: https://movai.atlassian.net/browse/FP-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2411: Only save params when necessary

- CHANGELOG.md
- src/decorators/withMenuHandler.jsx
[FP-2414](https://movai.atlassian.net/browse/FP-2414)
* Fixed an issue where we were always removing the bookmarks, even when not needed
[FP-2414]: https://movai.atlassian.net/browse/FP-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2414: Fixed an issue where we were always removing the bookmarks, even when not needed

- src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
[FP-2433](https://movai.atlassian.net/browse/FP-2433)
* A bug was introduced with [#111](https://github.com/MOV-AI/frontend-npm-lib-ide/pull/111) where we were using Node.defaults, as the default validation wether we should save to Database or not, when we should actually confirm with the template defaults.
[FP-2433]: https://movai.atlassian.net/browse/FP-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2433: Now correctly using template defaults

- CHANGELOG.md
- src/editors/Node/view/components/IOConfig/IOConfig.jsx
[FP-2427](https://movai.atlassian.net/browse/FP-2427)
* Update node instances when port messages change
[FP-2427]: https://movai.atlassian.net/browse/FP-2427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2427: Update node instances when port messages change

- CHANGELOG.md
- src/editors/Flow/model/Flow.js
- src/editors/Flow/model/subModels/ExposedPorts/ExposedPortsManager.js
[FP-2467](https://movai.atlassian.net/browse/FP-2467)
* We are now correctly deleting exposed ports on node deletion
[FP-2467]: https://movai.atlassian.net/browse/FP-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2467: We are now correctly deleting exposed ports on node deletion

- CHANGELOG.md
- src/editors/Flow/model/Flow.js
[FP-2535](https://movai.atlassian.net/browse/FP-2535)
* Fixed issue with deleting subflows from flow
[FP-2535]: https://movai.atlassian.net/browse/FP-2535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2535: Fixed issue with deleting subflows from flow

- CHANGELOG.md
- src/models/subModels/Parameter/ParameterWithType.js
- [FP-2540 - Duplicated code on the new merge request](https://movai.atlassian.net/browse/FP-2540)
> Fp 2540 duplicated code on the new merge request

- CHANGELOG.md
- src/editors/Flow/view/Components/FlowBottomBar/FlowBottomBar.jsx
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Components/interface/MainInterface.js
- src/editors/Flow/view/Core/Graph/GraphBase.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Views/BaseFlow.jsx
- [FP-2541 - Invalid links warning message is missing in removing port](https://movai.atlassian.net/browse/FP-2541)
> FP-2541 - Invalid links warning message is missing in removing port

- CHANGELOG.md
- src/editors/Flow/view/Components/FlowBottomBar/FlowBottomBar.jsx
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Components/interface/MainInterface.js
- src/editors/Flow/view/Core/Graph/GraphBase.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Views/BaseFlow.jsx
Revert https://github.com/MOV-AI/frontend-npm-lib-ide/pull/173
> Revert "FP-2541 - Invalid links warning message is missing in removing port (#173)

- CHANGELOG.md
- package-lock.json
- package.json
- src/editors/Flow/view/Core/Graph/GraphBase.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Views/BaseFlow.jsx
* FP-2542: Removed code that prevented flow validations from running (#174)
* Removed code that prevented flow validations from running
* Removed unused code, setShowWarnings to true by default
* removed unused comment
> New release (#176)

- CHANGELOG.md
- src/plugins/DocManager/DocManager.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
[FP-2527](https://movai.atlassian.net/browse/FP-2527)
* Preventing the reload of a new doc when it's closed
* Fixed some SonarQube errors
[FP-2527]: https://movai.atlassian.net/browse/FP-2527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2527: Preventing the reload of a new doc when it's closed

- src/editors/Node/view/components/hooks/useKeyValueMethods.js
[FP-2559 - Data-testids for IDE - Node](https://movai.atlassian.net/browse/FP-2559)
> Changes output_name to parameteres_output_name

- src/editors/_shared/hooks/DataTypes/types/BooleanType.js
[FP-2556 - Data-testids for IDE - Flow](https://movai.atlassian.net/browse/FP-2556)
> Adds data test-id to checkbox

- package-lock.json
- package.json
Update styles reference (lib-ide was referencing another version).
> Bump styles version

- src/editors/Flow/model/Flow.js
[FP-2585](https://movai.atlassian.net/browse/FP-2585)
* Added optional chaining to prevent crash
[FP-2585]: https://movai.atlassian.net/browse/FP-2585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2585: Added optional chaining to prevent crash

- CHANGELOG.md
- src/decorators/withBookmarks.jsx
- src/engine/ReactPlugin/ToolReactPlugin.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
[FP-2477](https://movai.atlassian.net/browse/FP-2477)
* Added validation to not close drawer
* Fixed some sonarQube issues
**The only real, needed change here is in `src/plugins/views/Tabs/hooks/useTabLayout.js` on lines 8, and 692. The rest are SonarQube fixes**
[FP-2477]: https://movai.atlassian.net/browse/FP-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2477: Added validation to not close drawer

- CHANGELOG.md
- src/plugins/Dialog/Dialog.js
- src/plugins/Dialog/components/FormDialog/FormDialog.jsx
- src/utils/Utils.js
[FP-2560](https://movai.atlassian.net/browse/FP-2560)
* Set default for validation Name to empty to prevent error
* Correct some Sonarqube issues 
[FP-2560]: https://movai.atlassian.net/browse/FP-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2560: Set default for validation Name to empty to prevent error

- package-lock.json
- package.json
Update lib-ide to 1.0.0-59 version
> Update lib-ide Version to 1.0.0-59

- package-lock.json
- package.json
> Bumped to version 69

- package-lock.json
- package.json
> Bumped version to 69

- src/decorators/withBookmarks.jsx
- src/plugins/views/Tabs/hooks/useTabLayout.js
[FP-24277](https://movai.atlassian.net/browse/FP-24277)
* Since my previous PR #221 didn't quite fix the real issue this one should do it
* No longer closing drawer on tab change
> FP-2477: No longer closing drawer on tab change

- CHANGELOG.md
- src/decorators/withBookmarks.jsx
- src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
- [FP-2604 - Left menu disappears when opening scene in IDE](https://movai.atlassian.net/browse/FP-2604)
> Fp 2604 left menu disappears when opening scene in ide

- CHANGELOG.md
- package-lock.json
- package.json
- src/decorators/styles.js
- src/editors/Flow/view/Components/FlowTopBar/styles.js
- src/editors/_shared/Search/Search.jsx
- [FP-2618](https://movai.atlassian.net/browse/FP-2618): Search for parameters not working
[FP-2618]: https://movai.atlassian.net/browse/FP-2618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2618 - Search for parameters not working

- CHANGELOG.md
- package-lock.json
- package.json
- src/decorators/styles.js
- src/editors/Flow/view/Components/FlowTopBar/styles.js
- src/editors/_shared/Search/Search.jsx
- [FP-2618](https://movai.atlassian.net/browse/FP-2618): Search for parameters not working
[FP-2618]: https://movai.atlassian.net/browse/FP-2618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 1.0.0-75

- package-lock.json
- package.json
- fix some problems with websocket logs
> Release 1.0.1-2

- package.json
- pnpm-lock.yaml
- src/editors/Flow/view/Components/Menus/styles.js
- src/editors/Flow/view/Components/Menus/sub-components/collapsibleSections/PropertyItem.jsx
- [FP-2731](https://movai.atlassian.net/browse/FP-2731) Property persistent is not editable (continuation)
- Update scripts (no impact)
- publicPath simplification (continuation)
- Update lib-react (no impact)
[FP-2731]: https://movai.atlassian.net/browse/FP-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [1.1.2-10]: Property persistent is not editable (2731)

- package.json
- pnpm-lock.yaml
- src/editors/Flow/view/Flow.jsx
- src/plugins/views/Tabs/hooks/useTabLayout.js
- Render right menu even if Flow load takes a long time
- Make sure drawer url is set when closing tabs
> [1.1.2-11]: render right menu even if Flow loading takes a long time, make sure the drawer url is set when closing tabs.

- package.json
- pnpm-lock.yaml
- src/editors/Callback/view/Callback.jsx
- src/editors/Configuration/view/Configuration.jsx
- src/editors/Node/view/Node.jsx
- Ensure bookmarks are always added to the right side
> [1.1.2-12]: Ensure bookmarks are always added to the right side

- package.json
- pnpm-lock.yaml
- src/plugins/views/MainMenu/MainMenu.jsx
- src/plugins/views/Tabs/hooks/useTabLayout.js
- [FP-2746](https://movai.atlassian.net/browse/FP-2746): Unsaved new document doesnt disapear when closed and not saved
- [FP-2749](https://movai.atlassian.net/browse/FP-2749): Tooltip duplicated
[FP-2746]: https://movai.atlassian.net/browse/FP-2746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-2749]: https://movai.atlassian.net/browse/FP-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [1.1.2-13]: 2746 + 2749

- package.json
- pnpm-lock.yaml
- src/editors/Flow/view/Components/Menus/styles.js
- src/editors/Flow/view/Components/Menus/sub-components/MenuDetails.jsx
- src/plugins/hosts/DrawerPanel/DrawerPanel.jsx
- Fix local keybind path
- Fix node menu title size
> [1.1.2-18]: Fix local keybind path

- src/engine/ReactPlugin/EditorReactPlugin.js
- src/engine/ReactPlugin/ToolReactPlugin.js
- src/plugins/views/Tabs/hooks/useTabLayout.js
- [FP-2771](https://movai.atlassian.net/browse/FP-2771): Scene - scene explorer sticky when closing a scene without saving changes
[FP-2771]: https://movai.atlassian.net/browse/FP-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [1.1.2-19]: Scene - scene explorer sticky when closing a scene without saving changes

- CHANGELOG.md
- src/editors/Flow/view/Components/Links/BaseLink.js
- src/editors/Flow/view/Components/Links/BaseLink.test.js
- src/editors/Flow/view/Components/Nodes/BaseNode/BasePort.js
[FP-2529](https://movai.atlassian.net/browse/FP-2529)
* Added `data-testid`'s to flow links.
* Created and added a couple of unit tests to BaseLink
[FP-2529]: https://movai.atlassian.net/browse/FP-2529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2529: Add data-testid to links. Added unit testing to BaseLink

- CHANGELOG.md
- src/App/BaseApp.js
- [FP-2874](https://movai.atlassian.net/browse/FP-2874): IDE app version not correct
[FP-2874]: https://movai.atlassian.net/browse/FP-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2874-IDE-app-version-not-correct

- CHANGELOG.md
- src/editors/Configuration/view/Configuration.jsx
- src/editors/Flow/view/Flow.jsx
- src/engine/ReactPlugin/EditorReactPlugin.js
- src/plugins/DocManager/DocManager.js
- [FP-2882](https://movai.atlassian.net/browse/FP-2882): Clicking in the bar under the documents loses context, not easy to get back
[FP-2882]: https://movai.atlassian.net/browse/FP-2882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2882-Clicking-in-the-bar-under-the-documents-loses-context-not-easy-to-get-back

- CHANGELOG.md
> Bump version 1.2.8

- package.json
Updates fe-lib-ide version to 1.2.8
> Updates fe-lib-ide version

- CHANGELOG.md
- src/editors/Flow/view/Components/interface/MainInterface.js
- [FP-2981](https://movai.atlassian.net/browse/FP-2981): IDE - Copy subFlow doesn't work
[FP-2981]: https://movai.atlassian.net/browse/FP-2981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2981: IDE - Copy subFlow doesn't work

- CHANGELOG.md
- src/plugins/Dialog/Dialog.js
- src/utils/Constants.js
- src/utils/keybinds.js
[FP-2976](https://movai.atlassian.net/browse/FP-2976)
[FP-2979](https://movai.atlassian.net/browse/FP-2979)
- Fixed the infinite modals issue
- Also fixed another ticket where we couldn't use normal browser keybinds when in a modal
[FP-2976]: https://movai.atlassian.net/browse/FP-2976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-2979]: https://movai.atlassian.net/browse/FP-2979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2976: Added DIALOG scope on open and restore it on close dialog

- src/App/BaseApp.js
- src/utils/keybinds.js
[FP-2976](https://movai.atlassian.net/browse/FP-2976)
* Removed the `/` in the end of the `urls` when scope not needed.
[FP-2976]: https://movai.atlassian.net/browse/FP-2976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2976: Remove unused slash when scope is not passed

- CHANGELOG.md
- package.json
- [FP-3068](https://movai.atlassian.net/browse/FP-3068): Inconsitencies on Keybindings
[FP-3068]: https://movai.atlassian.net/browse/FP-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release lib-ide 1.4.3

- CHANGELOG.md
- src/editors/Node/view/Node.jsx
- [FP-3027](https://movai.atlassian.net/browse/FP-3027): IDE - Hide container configuration on nodes
[FP-3027]: https://movai.atlassian.net/browse/FP-3027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3027: IDE - Hide container configuration on node

- CHANGELOG.md
- src/editors/Flow/view/Components/Explorer/styles.js
- [FP-3080](https://movai.atlassian.net/browse/FP-3080): IDE - Fix Node preview banner width
[FP-3080]: https://movai.atlassian.net/browse/FP-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3080: IDE - Fix Node preview banner height

- CHANGELOG.md
- src/editors/Flow/view/Components/interface/canvas.js
[FP-1013](https://movai.atlassian.net/browse/FP-1013)
* Optimize Flow shift select nodes
[FP-1013]: https://movai.atlassian.net/browse/FP-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-1013: Optimize Flow shift select nodes

- .devcontainer/devcontainer.json
- CHANGELOG.md
- README.md
- [FP-3138](https://movai.atlassian.net/browse/FP-3138): Not able to use dev container in all frontend repos
[FP-3138]: https://movai.atlassian.net/browse/FP-3138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3138: Not able to use dev container in all frontend repos

- CHANGELOG.md
- src/editors/Flow/model/subModels/NodeInstance/NodeInstance.js
- src/editors/Flow/view/Components/Nodes/BaseNode/BaseNode.js
- src/editors/Flow/view/Components/Nodes/ClassicNode.js
- src/editors/Flow/view/Components/Nodes/ContainerNode.js
- src/editors/Flow/view/Components/Nodes/TreeView/TreeClassicNode.js
- src/editors/Flow/view/Components/Nodes/TreeView/TreeContainerNode.js
- src/editors/Flow/view/Components/interface/MainInterface.js
- src/editors/Flow/view/Components/interface/MainInterface.test.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Flow.test.jsx
- src/utils/Utils.js
[FP-3154](https://movai.atlassian.net/browse/FP-3154)
* Fix copy paste not carrying instance parameters
[FP-3154]: https://movai.atlassian.net/browse/FP-3154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3154: Fix copy paste not carrying instance parameters

- CHANGELOG.md
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
[FP-3202](https://movai.atlassian.net/browse/FP-3202)
* Removes snackbar when loading flow
[FP-3202]: https://movai.atlassian.net/browse/FP-3202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3202: Removes snackbar when loading flow

- CHANGELOG.md
- src/editors/Node/view/Node.jsx
[FP-3162](https://movai.atlassian.net/browse/FP-3162)
* Added check for empty name
* Translated error messages shown to the user
[FP-3162]: https://movai.atlassian.net/browse/FP-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3162: Added check for empty name, translated error messages shown to the user

- CHANGELOG.md
- src/utils/Constants.js
[FP-3208](https://movai.atlassian.net/browse/FP-3208)
* Broaden the Parameter Name validation to allow _ or __ starting names
[FP-3208]: https://movai.atlassian.net/browse/FP-3208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3208: Broaden the Parameter Name validation to allow _ or __ starting names

- CHANGELOG.md
- src/editors/_shared/KeyValueTable/KeyValueEditorDialog.jsx
- src/editors/_shared/KeyValueTable/ParametersEditorDialog.jsx
- src/editors/_shared/hooks/DataTypes/AbstractDataType.js
- src/editors/_shared/hooks/DataTypes/types/ArrayType.js
- [FP-3212](https://movai.atlassian.net/browse/FP-3212): Unable to create a type Array flow parameter with a list of strings
[FP-3212]: https://movai.atlassian.net/browse/FP-3212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3212: Unable to create a type Array flow parameter with a list of strings

- CHANGELOG.md
- src/editors/Flow/view/Views/BaseFlow.jsx
- [FP-2905](https://movai.atlassian.net/browse/FP-2905): When changing a node template, the node is not updated in the flow
[FP-2905]: https://movai.atlassian.net/browse/FP-2905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-2905: When changing a node template, the node is not updated in the flow

- CHANGELOG.md
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Flow.jsx
- src/utils/Constants.js
- [FP-3163](https://movai.atlassian.net/browse/FP-3163): Clicking on the flow of a member opens the flow with the master
[FP-3163]: https://movai.atlassian.net/browse/FP-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3163: Clicking on the flow of a member opens the flow with the master

- CHANGELOG.md
- package.json
- src/editors/Flow/view/Components/FlowTopBar/FlowTopBar.jsx
- src/editors/Flow/view/Components/Nodes/BaseNode/BasePort.js
- src/editors/Flow/view/Components/Tooltips/PortTooltip.jsx
- src/editors/Flow/view/Constants/constants.js
- src/editors/Flow/view/Flow.jsx
- src/editors/Flow/view/Views/BaseFlow.jsx
- src/utils/Constants.js
- [FP-3163](https://movai.atlassian.net/browse/FP-3163): Clicking on the flow of a member opens the flow with the master
- [FP-2905](https://movai.atlassian.net/browse/FP-2905): When changing a node template, the node is not updated in the flow
- [FP-3081](https://movai.atlassian.net/browse/FP-3081): Port Modal lingers frequently
[FP-3163]: https://movai.atlassian.net/browse/FP-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-2905]: https://movai.atlassian.net/browse/FP-2905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-3081]: https://movai.atlassian.net/browse/FP-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 2.6.3

- CHANGELOG.md
- src/utils/Workspace.js
[FP-3262](https://movai.atlassian.net/browse/FP-3262)
* Added robot version to Workspace baseKey
[FP-3262]: https://movai.atlassian.net/browse/FP-3262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FP-3262: Added robot version to Workspace baseKey

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- [FP-3350](https://movai.atlassian.net/browse/FP-3350): Change in an editor and then logout
- [FP-3355](https://movai.atlassian.net/browse/FP-3355): Fleetboard: Logs not updating
- [FP-3192](https://movai.atlassian.net/browse/FP-3192): Should not be possible to start a node from a flow not running
[FP-3350]: https://movai.atlassian.net/browse/FP-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-3355]: https://movai.atlassian.net/browse/FP-3355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FP-3192]: https://movai.atlassian.net/browse/FP-3192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release lib-ide 2.7.3
